spring:
  profiles:
    active: local
server:
  port: 8081
---
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MODE=MYSQL
      username: test
      password: test
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    activate:
      on-profile:
  sql:
    init:
      platform: h2
